language: swift
os: osx
osx_image: xcode9.2
before_script:
- gem install xcpretty
script:
- swift package generate-xcodeproj
- xcodebuild -list
- set -o pipefail && xcodebuild -scheme SwiftRoaring -enableCodeCoverage YES clean build test | xcpretty
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'TaskerServerLib'
