#if !canImport(ObjectiveC)
import XCTest

extension swiftRoaringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__swiftRoaringTests = [
        ("testAdd", testAdd),
        ("testAddingRemoving", testAddingRemoving),
        ("testAnd", testAnd),
        ("testAndNot", testAndNot),
        ("testBase64", testBase64),
        ("testClear", testClear),
        ("testDescription", testDescription),
        ("testEquals", testEquals),
        ("testFlip", testFlip),
        ("testHashValue", testHashValue),
        ("testInitArray", testInitArray),
        ("testInitCapacity", testInitCapacity),
        ("testInitRange", testInitRange),
        ("testIterator", testIterator),
        ("testJaccardIndex", testJaccardIndex),
        ("testOptimisations", testOptimisations),
        ("testOr", testOr),
        ("testPortableSerialize", testPortableSerialize),
        ("testPrinting", testPrinting),
        ("testRemove", testRemove),
        ("testSelect", testSelect),
        ("testSerialize", testSerialize),
        ("testStatistics", testStatistics),
        ("testSubset", testSubset),
        ("testToArray", testToArray),
        ("testXor", testXor),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(swiftRoaringTests.__allTests__swiftRoaringTests),
    ]
}
#endif
