name: Swift on Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests-linux:
    strategy:
      matrix:
        swift: ["6"]
        ubuntu: ["ubuntu-24.04"]

    name: SwiftPM build in Swift ${{ matrix.swift }} on ${{ matrix.ubuntu }}
    runs-on: ${{ matrix.ubuntu }}
    steps:
      - name: Log versions
        run: echo "Target Swift ${{ matrix.swift }} on ${{ matrix.ubuntu }}"
      - name: Setup Swift version
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: linuxmain
        run: |
          echo "::notice title=Build Environment::Running on ${{ matrix.os }}"
          swift --version
          swift build
          swift test
      - name: Build
        run: swift build
      - name: Test
        run: swift test
  tests-macOS:
    strategy:
      fail-fast: false
      matrix:
        swift: ["5", "6"]
        destination: [macOS]

    name: SwiftPM macOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
      
        uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test
