name: Swift on macOS (latest)

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests-macOS:
    strategy:
      fail-fast: false
      matrix:
        swift: ["5", "6"]
        destination: [macOS]

    name: SwiftPM macOS
    runs-on: macOS-latest
    steps:
      - name: Checkout      
        uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: swift test
